DELETE PS_PRCSJOBDEFN
    WHERE PRCSJOBNAME = '<Job>';
    
DELETE PS_PRCSJOBDEFNLANG
    WHERE PRCSJOBNAME = '<Job>';
    
DELETE PS_PRCSJOBGRP
    WHERE PRCSJOBNAME = '<Job>';
    
DELETE PS_PRCSJOBPNL
    WHERE PRCSJOBNAME = '<Job>';
    
DELETE PS_PRCSJOBITEM
    WHERE PRCSJOBNAME = '<Job>';

DELETE PS_PRCSJOBMESSAGE
    WHERE PRCSJOBNAME = '<Job>'
    
-- Si quedan procesos en el scheduler
DELETE PSPRCSRQST WHERE PRCSJOBNAME = '<Job>';